name: mktusf
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: mktusf
  id: 28701bbc-2a62-4de6-9dcf-bb0ae932837a
  xdebug: true
services:
  appserver:
    type: php
    config:
      php: conf/php.ini
    overrides:
      environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/web" }}}}
  node:
    type: node
#    build:
#      - "cd $LANDO_MOUNT/web/themes/custom/myusf && npm install && gulp"
    globals:
      gulp-cli: "latest"
tooling:
  npm:
    service: node
  gulp:
    service: node
  robo:
    service: appserver
    cmd: /app/vendor/bin/robo --load-from=/app
  test:
    service: appserver
    cmd: app/vendor/bin/robo test
  drush:
    service: appserver
    cmd: drush --uri=https://dgreat.lndo.site
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
